apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-finances-data
  namespace: my-finances
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
