apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-dns-records
  namespace: home-dns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Mi
