apiVersion: v1
kind: Service
metadata:
  name: home-dns
  namespace: home-dns
spec:
  type: NodePort
  selector:
    app: home-dns
  ports:
    - name: dns-udp
      port: 30053
      targetPort: 30053
      nodePort: 31053
      protocol: UDP

    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
