apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
spec:
  project: default
  source:
    repoURL: https://github.com/Brad-Davy/pi-k3s.git
    targetRevision: main
    path: apps/infrastructure
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
