apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-finances
  namespace: my-finances
spec:
  ingressClassName: traefik
  rules:
    - host: my-finances.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-finances
                port:
                  number: 8080
